Repository brain-tec/purchase-workflow, pull requests merged in 2022-09, with the labels that each got.

#743 Syncing from upstream OCA/purchase-workflow (12.0)
  purchase_order_approved/i18n/pt_BR.po
  purchase_start_end_dates/i18n/pt.po
Labels: 12.0

#744 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_stock_price_unit_sync/README.rst
  purchase_stock_price_unit_sync/__init__.py
  purchase_stock_price_unit_sync/__manifest__.py
  purchase_stock_price_unit_sync/i18n/purchase_stock_price_unit_sync.pot
  purchase_stock_price_unit_sync/models/__init__.py
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/readme/CONTRIBUTORS.rst
  purchase_stock_price_unit_sync/readme/DESCRIPTION.rst
  purchase_stock_price_unit_sync/static/description/icon.png
  purchase_stock_price_unit_sync/static/description/index.html
  purchase_stock_price_unit_sync/tests/__init__.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_stock_price_unit_sync/odoo/addons/purchase_stock_price_unit_sync
  setup/purchase_stock_price_unit_sync/setup.py
Labels: 14.0

#745 Syncing from upstream OCA/purchase-workflow (13.0)
  README.md
  purchase_order_uninvoiced_amount/__manifest__.py
  purchase_order_uninvoiced_amount/models/purchase_order.py
Labels: 13.0

#746 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_order_uninvoiced_amount/__manifest__.py
  purchase_order_uninvoiced_amount/models/purchase_order.py
Labels: 14.0

#747 Syncing from upstream OCA/purchase-workflow (13.0)
  README.md
  purchase_landed_cost/__manifest__.py
  purchase_landed_cost/views/account_move_view.xml
Labels: 13.0

#748 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_deposit/i18n/es.po
Labels: 14.0

#749 Syncing from upstream OCA/purchase-workflow (15.0)
  purchase_deposit/i18n/arp.po
  purchase_deposit/i18n/es.po
Labels: 15.0

#750 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_manual_delivery/__manifest__.py
  purchase_manual_delivery/wizard/create_manual_stock_picking.py
  purchase_request/__manifest__.py
  purchase_request/models/purchase_request_line.py
Labels: 14.0

#752 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_location_by_line/README.rst
  purchase_location_by_line/__init__.py
  purchase_location_by_line/__manifest__.py
  purchase_location_by_line/i18n/ca.po
  purchase_location_by_line/i18n/de.po
  purchase_location_by_line/i18n/es.po
  purchase_location_by_line/i18n/es_MX.po
  purchase_location_by_line/i18n/es_PE.po
  purchase_location_by_line/i18n/fi.po
  purchase_location_by_line/i18n/fr.po
  purchase_location_by_line/i18n/gl.po
  purchase_location_by_line/i18n/hr.po
  purchase_location_by_line/i18n/it.po
  purchase_location_by_line/i18n/nl_NL.po
  purchase_location_by_line/i18n/pt_BR.po
  purchase_location_by_line/i18n/pt_PT.po
  purchase_location_by_line/i18n/purchase_location_by_line.pot
  purchase_location_by_line/i18n/ro.po
  purchase_location_by_line/i18n/sl.po
  purchase_location_by_line/models/__init__.py
  purchase_location_by_line/models/purchase.py
  purchase_location_by_line/models/stock_picking.py
  purchase_location_by_line/readme/CONTRIBUTORS.rst
  purchase_location_by_line/readme/DESCRIPTION.rst
  purchase_location_by_line/static/description/icon.png
  purchase_location_by_line/static/description/index.html
  purchase_location_by_line/tests/__init__.py
  purchase_location_by_line/tests/test_purchase_delivery.py
  purchase_location_by_line/views/purchase_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_location_by_line/odoo/addons/purchase_location_by_line
  setup/purchase_location_by_line/setup.py
Labels: 15.0

#753 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_allowed_product/i18n/fr.po
  purchase_analytic_global/i18n/fr.po
  purchase_partner_incoterm/README.rst
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/migrations/14.0.3.0.0/post-migration.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/readme/CONTRIBUTORS.rst
  purchase_partner_incoterm/static/description/index.html
  purchase_partner_incoterm/views/partner_view.xml
Labels: 14.0

#754 Syncing from upstream OCA/purchase-workflow (13.0)
  purchase_order_type/i18n/es.po
Labels: 13.0

#755 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_order_qty_change_no_recompute/README.rst
  purchase_order_qty_change_no_recompute/__init__.py
  purchase_order_qty_change_no_recompute/__manifest__.py
  purchase_order_qty_change_no_recompute/i18n/purchase_order_qty_change_no_recompute.pot
  purchase_order_qty_change_no_recompute/models/__init__.py
  purchase_order_qty_change_no_recompute/models/purchase_order.py
  purchase_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  purchase_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  purchase_order_qty_change_no_recompute/readme/USAGE.rst
  purchase_order_qty_change_no_recompute/static/description/icon.png
  purchase_order_qty_change_no_recompute/static/description/index.html
  purchase_order_qty_change_no_recompute/tests/__init__.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_order_qty_change_no_recompute/odoo/addons/purchase_order_qty_change_no_recompute
  setup/purchase_order_qty_change_no_recompute/setup.py
Labels: 14.0

#756 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_advance_payment/README.rst
  purchase_advance_payment/__init__.py
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/i18n/fr.po
  purchase_advance_payment/i18n/purchase_advance_payment.pot
  purchase_advance_payment/models/__init__.py
  purchase_advance_payment/models/payment.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/readme/CONTRIBUTORS.rst
  purchase_advance_payment/readme/DESCRIPTION.rst
  purchase_advance_payment/readme/USAGE.rst
  purchase_advance_payment/security/ir.model.access.csv
  purchase_advance_payment/static/description/icon.png
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/__init__.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
  purchase_advance_payment/views/purchase_view.xml
  purchase_advance_payment/wizard/__init__.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_advance_payment/odoo/addons/purchase_advance_payment
  setup/purchase_advance_payment/setup.py
Labels: 15.0

#757 Syncing from upstream OCA/purchase-workflow (12.0)
  purchase_order_approved/i18n/pt_BR.po
Labels: 12.0

#758 Syncing from upstream OCA/purchase-workflow (13.0)
  purchase_order_approved/i18n/pt_BR.po
Labels: 13.0

#759 Syncing from upstream OCA/purchase-workflow (14.0)
  product_supplier_code_purchase/i18n/pt_BR.po
  purchase_order_approved/i18n/pt_BR.po
  purchase_order_type/i18n/pt_BR.po
  purchase_request/i18n/pt_BR.po
Labels: 14.0

#760 [t131839] 15.0 mig purchase partner incoterm
  purchase_partner_incoterm/README.rst
  purchase_partner_incoterm/__init__.py
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/i18n/purchase_partner_incoterm.pot
  purchase_partner_incoterm/models/__init__.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/readme/CONTRIBUTORS.rst
  purchase_partner_incoterm/readme/CREDITS.rst
  purchase_partner_incoterm/readme/DESCRIPTION.rst
  purchase_partner_incoterm/static/description/icon.png
  purchase_partner_incoterm/static/description/index.html
  purchase_partner_incoterm/views/partner_view.xml
  setup/purchase_partner_incoterm/odoo/addons/purchase_partner_incoterm
  setup/purchase_partner_incoterm/setup.py
Labels: 15.0.project_sa_650

#761 [t129011] fix purchase_request: purchase_request_id mapping
  purchase_request/models/stock_move.py
Labels: 15.0.project_gr_578

#762 Syncing from upstream OCA/purchase-workflow (13.0)
  README.md
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/models/blanket_orders.py
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: 13.0

#763 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/report/report.xml
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: 14.0

#764 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  oca_dependencies.txt
  purchase_exception/README.rst
  purchase_exception/__init__.py
  purchase_exception/__manifest__.py
  purchase_exception/data/purchase_exception_data.xml
  purchase_exception/i18n/fr.po
  purchase_exception/i18n/purchase_exception.pot
  purchase_exception/i18n/zh_CN.po
  purchase_exception/models/__init__.py
  purchase_exception/models/exception_rule.py
  purchase_exception/models/purchase.py
  purchase_exception/models/purchase_line.py
  purchase_exception/readme/CONTRIBUTORS.rst
  purchase_exception/readme/DESCRIPTION.rst
  purchase_exception/security/ir.model.access.csv
  purchase_exception/static/description/icon.png
  purchase_exception/static/description/index.html
  purchase_exception/tests/__init__.py
  purchase_exception/tests/test_purchase_exception.py
  purchase_exception/views/purchase_view.xml
  purchase_exception/wizard/__init__.py
  purchase_exception/wizard/purchase_exception_confirm.py
  purchase_exception/wizard/purchase_exception_confirm_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_exception/odoo/addons/purchase_exception
  setup/purchase_exception/setup.py
Labels: 15.0

#765 Syncing from upstream OCA/purchase-workflow (13.0)
  README.md
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: 13.0

#766 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: 14.0

#767 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/views/purchase_blanket_order_views.xml
Labels: 15.0
