Repository brain-tec/purchase-workflow, pull requests merged in 2022-10, with the labels that each got.

#768 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_order_line_price_history/README.rst
  purchase_order_line_price_history/__init__.py
  purchase_order_line_price_history/__manifest__.py
  purchase_order_line_price_history/i18n/de.po
  purchase_order_line_price_history/i18n/es.po
  purchase_order_line_price_history/i18n/fr.po
  purchase_order_line_price_history/i18n/nl_NL.po
  purchase_order_line_price_history/i18n/purchase_order_line_price_history.pot
  purchase_order_line_price_history/readme/CONTRIBUTORS.rst
  purchase_order_line_price_history/readme/DESCRIPTION.rst
  purchase_order_line_price_history/readme/ROADMAP.rst
  purchase_order_line_price_history/readme/USAGE.rst
  purchase_order_line_price_history/security/ir.model.access.csv
  purchase_order_line_price_history/static/description/icon.png
  purchase_order_line_price_history/static/description/index.html
  purchase_order_line_price_history/tests/__init__.py
  purchase_order_line_price_history/tests/test_purchase_order_line_price_history.py
  purchase_order_line_price_history/views/purchase_views.xml
  purchase_order_line_price_history/wizards/__init__.py
  purchase_order_line_price_history/wizards/purchase_order_line_price_history.py
  purchase_order_line_price_history/wizards/purchase_order_line_price_history.xml
  purchase_partner_incoterm/README.rst
  purchase_partner_incoterm/__init__.py
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/i18n/purchase_partner_incoterm.pot
  purchase_partner_incoterm/models/__init__.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/readme/CONTRIBUTORS.rst
  purchase_partner_incoterm/readme/CREDITS.rst
  purchase_partner_incoterm/readme/DESCRIPTION.rst
  purchase_partner_incoterm/static/description/icon.png
  purchase_partner_incoterm/static/description/index.html
  purchase_partner_incoterm/views/partner_view.xml
  purchase_partner_incoterm/views/purchase_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_order_line_price_history/odoo/addons/purchase_order_line_price_history
  setup/purchase_order_line_price_history/setup.py
  setup/purchase_partner_incoterm/odoo/addons/purchase_partner_incoterm
  setup/purchase_partner_incoterm/setup.py
Labels: 15.0

#769 Syncing from upstream OCA/purchase-workflow (12.0)
  procurement_purchase_no_grouping/i18n/pt_BR.po
  product_supplier_code_purchase/i18n/pt_BR.po
  purchase_allowed_product/i18n/pt_BR.po
  purchase_commercial_partner/i18n/pt_BR.po
  purchase_date_planned_manual/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_discount/i18n/pt_BR.po
  purchase_landed_cost/i18n/pt_BR.po
  purchase_location_by_line/i18n/pt_BR.po
  purchase_minimum_amount/i18n/pt_BR.po
  purchase_open_qty/i18n/pt_BR.po
  purchase_order_line_description/i18n/pt_BR.po
  purchase_order_line_stock_available/i18n/pt_BR.po
  purchase_order_type/i18n/pt_BR.po
  purchase_picking_state/i18n/pt_BR.po
  purchase_request/i18n/pt_BR.po
  purchase_triple_discount/i18n/pt_BR.po
Labels: 12.0

#770 Syncing from upstream OCA/purchase-workflow (14.0)
  procurement_purchase_no_grouping/i18n/pt_BR.po
  product_supplier_code_purchase/i18n/pt_BR.po
  purchase_allowed_product/i18n/pt_BR.po
  purchase_cancel_reason/i18n/pt_BR.po
  purchase_commercial_partner/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_discount/i18n/pt_BR.po
  purchase_fop_shipping/i18n/pt_BR.po
  purchase_location_by_line/i18n/pt_BR.po
  purchase_minimum_amount/i18n/pt_BR.po
  purchase_open_qty/i18n/pt_BR.po
  purchase_order_type/i18n/pt_BR.po
  purchase_picking_state/i18n/pt_BR.po
  purchase_request/i18n/pt_BR.po
  purchase_request_to_requisition/i18n/pt_BR.po
  purchase_triple_discount/i18n/pt_BR.po
Labels: 14.0

#771 Syncing from upstream OCA/purchase-workflow (15.0)
  procurement_purchase_no_grouping/i18n/pt_BR.po
  purchase_default_terms_conditions/i18n/pt_BR.po
  purchase_delivery_split_date/i18n/pt_BR.po
  purchase_discount/i18n/pt_BR.po
  purchase_location_by_line/i18n/pt_BR.po
  purchase_order_type/i18n/pt_BR.po
  purchase_request/i18n/pt_BR.po
Labels: 15.0

#772 [t130277][15.0-mig] purchase order secondary unit
  README.md
  oca_dependencies.txt
  purchase_blanket_order/__manifest__.py
  purchase_blanket_order/report/templates.xml
  purchase_blanket_order/views/purchase_blanket_order_views.xml
  purchase_exception/README.rst
  purchase_exception/__init__.py
  purchase_exception/__manifest__.py
  purchase_exception/data/purchase_exception_data.xml
  purchase_exception/i18n/fr.po
  purchase_exception/i18n/purchase_exception.pot
  purchase_exception/i18n/zh_CN.po
  purchase_exception/models/__init__.py
  purchase_exception/models/exception_rule.py
  purchase_exception/models/purchase.py
  purchase_exception/models/purchase_line.py
  purchase_exception/readme/CONTRIBUTORS.rst
  purchase_exception/readme/DESCRIPTION.rst
  purchase_exception/security/ir.model.access.csv
  purchase_exception/static/description/icon.png
  purchase_exception/static/description/index.html
  purchase_exception/tests/__init__.py
  purchase_exception/tests/test_purchase_exception.py
  purchase_exception/views/purchase_view.xml
  purchase_exception/wizard/__init__.py
  purchase_exception/wizard/purchase_exception_confirm.py
  purchase_exception/wizard/purchase_exception_confirm_view.xml
  purchase_order_secondary_unit/README.rst
  purchase_order_secondary_unit/__init__.py
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/de.po
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/fr.po
  purchase_order_secondary_unit/i18n/ja.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/__init__.py
  purchase_order_secondary_unit/models/product_template.py
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_order_secondary_unit/readme/DESCRIPTION.rst
  purchase_order_secondary_unit/readme/USAGE.rst
  purchase_order_secondary_unit/static/description/icon.png
  purchase_order_secondary_unit/static/description/index.html
  purchase_order_secondary_unit/tests/__init__.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/product_views.xml
  purchase_order_secondary_unit/views/purchase_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_exception/odoo/addons/purchase_exception
  setup/purchase_exception/setup.py
  setup/purchase_order_secondary_unit/odoo/addons/purchase_order_secondary_unit
  setup/purchase_order_secondary_unit/setup.py
Labels: odoo_migration, 15.0.project_gr_578

#773 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_triple_discount/__manifest__.py
  purchase_triple_discount/i18n/de.po
  purchase_triple_discount/i18n/es.po
  purchase_triple_discount/i18n/es_MX.po
  purchase_triple_discount/i18n/es_PE.po
  purchase_triple_discount/i18n/fi.po
  purchase_triple_discount/i18n/fr.po
  purchase_triple_discount/i18n/hr.po
  purchase_triple_discount/i18n/it.po
  purchase_triple_discount/i18n/nl_NL.po
  purchase_triple_discount/i18n/pt_BR.po
  purchase_triple_discount/i18n/pt_PT.po
  purchase_triple_discount/i18n/purchase_triple_discount.pot
  purchase_triple_discount/i18n/ro.po
  purchase_triple_discount/i18n/sl.po
  purchase_triple_discount/i18n/zh_CN.po
  purchase_triple_discount/views/purchase_order_report.xml
Labels: 14.0

#774 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_request_substate/README.rst
  purchase_request_substate/__init__.py
  purchase_request_substate/__manifest__.py
  purchase_request_substate/data/purchase_request_substate_data.xml
  purchase_request_substate/data/purchase_substate_mail_template_data.xml
  purchase_request_substate/demo/purchase_request_substate_demo.xml
  purchase_request_substate/i18n/purchase_request_substate.pot
  purchase_request_substate/models/__init__.py
  purchase_request_substate/models/purchase_request.py
  purchase_request_substate/readme/CONTRIBUTORS.rst
  purchase_request_substate/readme/DESCRIPTION.rst
  purchase_request_substate/readme/USAGE.rst
  purchase_request_substate/static/description/icon.png
  purchase_request_substate/static/description/index.html
  purchase_request_substate/tests/__init__.py
  purchase_request_substate/tests/test_purchase_request_substate.py
  purchase_request_substate/views/purchase_request_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_request_substate/odoo/addons/purchase_request_substate
  setup/purchase_request_substate/setup.py
Labels: 14.0

#775 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_triple_discount/README.rst
  purchase_triple_discount/__init__.py
  purchase_triple_discount/__manifest__.py
  purchase_triple_discount/i18n/de.po
  purchase_triple_discount/i18n/es.po
  purchase_triple_discount/i18n/es_MX.po
  purchase_triple_discount/i18n/es_PE.po
  purchase_triple_discount/i18n/fi.po
  purchase_triple_discount/i18n/fr.po
  purchase_triple_discount/i18n/hr.po
  purchase_triple_discount/i18n/it.po
  purchase_triple_discount/i18n/nl_NL.po
  purchase_triple_discount/i18n/pt_BR.po
  purchase_triple_discount/i18n/pt_PT.po
  purchase_triple_discount/i18n/purchase_triple_discount.pot
  purchase_triple_discount/i18n/ro.po
  purchase_triple_discount/i18n/sl.po
  purchase_triple_discount/i18n/zh_CN.po
  purchase_triple_discount/models/__init__.py
  purchase_triple_discount/models/product_supplierinfo.py
  purchase_triple_discount/models/purchase_order.py
  purchase_triple_discount/models/res_partner.py
  purchase_triple_discount/readme/CONTRIBUTORS.rst
  purchase_triple_discount/readme/DESCRIPTION.rst
  purchase_triple_discount/readme/USAGE.rst
  purchase_triple_discount/report/__init__.py
  purchase_triple_discount/report/purchase_report.py
  purchase_triple_discount/static/description/icon.png
  purchase_triple_discount/static/description/index.html
  purchase_triple_discount/tests/__init__.py
  purchase_triple_discount/tests/test_purchase_discount.py
  purchase_triple_discount/views/product_supplierinfo_view.xml
  purchase_triple_discount/views/purchase_order_report.xml
  purchase_triple_discount/views/purchase_view.xml
  purchase_triple_discount/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_triple_discount/odoo/addons/purchase_triple_discount
  setup/purchase_triple_discount/setup.py
Labels: 15.0

#776 Syncing from upstream OCA/purchase-workflow (12.0)
  purchase_reception_status/i18n/fr.po
Labels: 12.0

#777 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_open_qty/README.rst
  purchase_open_qty/__init__.py
  purchase_open_qty/__manifest__.py
  purchase_open_qty/i18n/de.po
  purchase_open_qty/i18n/es.po
  purchase_open_qty/i18n/es_MX.po
  purchase_open_qty/i18n/es_PE.po
  purchase_open_qty/i18n/fi.po
  purchase_open_qty/i18n/fr.po
  purchase_open_qty/i18n/fr_BE.po
  purchase_open_qty/i18n/gl.po
  purchase_open_qty/i18n/hr.po
  purchase_open_qty/i18n/it.po
  purchase_open_qty/i18n/nl.po
  purchase_open_qty/i18n/nl_NL.po
  purchase_open_qty/i18n/pt_BR.po
  purchase_open_qty/i18n/pt_PT.po
  purchase_open_qty/i18n/purchase_open_qty.pot
  purchase_open_qty/i18n/ro.po
  purchase_open_qty/i18n/sl.po
  purchase_open_qty/i18n/vi_VN.po
  purchase_open_qty/i18n/zh_CN.po
  purchase_open_qty/init_hook.py
  purchase_open_qty/models/__init__.py
  purchase_open_qty/models/purchase_order.py
  purchase_open_qty/readme/CONTRIBUTORS.rst
  purchase_open_qty/readme/DESCRIPTION.rst
  purchase_open_qty/readme/USAGE.rst
  purchase_open_qty/static/description/icon.png
  purchase_open_qty/static/description/index.html
  purchase_open_qty/tests/__init__.py
  purchase_open_qty/tests/test_purchase_open_qty.py
  purchase_open_qty/views/purchase_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_open_qty/odoo/addons/purchase_open_qty
  setup/purchase_open_qty/setup.py
Labels: 15.0

#778 Syncing from upstream OCA/purchase-workflow (12.0)
  purchase_order_line_price_history/i18n/it.po
Labels: 12.0

#779 Syncing from upstream OCA/purchase-workflow (13.0)
  README.md
  purchase_origin_link/README.rst
  purchase_origin_link/__init__.py
  purchase_origin_link/__manifest__.py
  purchase_origin_link/i18n/purchase_origin_link.pot
  purchase_origin_link/models/__init__.py
  purchase_origin_link/models/purchase.py
  purchase_origin_link/readme/CONTRIBUTORS.rst
  purchase_origin_link/readme/DESCRIPTION.rst
  purchase_origin_link/static/description/icon.png
  purchase_origin_link/static/description/index.html
  purchase_origin_link/views/purchase_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_origin_link/odoo/addons/purchase_origin_link
  setup/purchase_origin_link/setup.py
Labels: 13.0

#780 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  sale_purchase_force_vendor/__manifest__.py
  sale_purchase_force_vendor/i18n/es.po
  sale_purchase_force_vendor/i18n/sale_purchase_force_vendor.pot
  sale_purchase_force_vendor/models/sale_order_line.py
  sale_purchase_force_vendor/tests/test_sale_purchase_force_vendor.py
  sale_purchase_force_vendor/views/sale_order_view.xml
Labels: 14.0

#781 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  product_form_purchase_link/__init__.py
  product_form_purchase_link/__manifest__.py
  product_form_purchase_link/i18n/fr.po
  product_form_purchase_link/i18n/product_form_purchase_link.pot
  product_form_purchase_link/models/__init__.py
  product_form_purchase_link/models/product_product.py
  product_form_purchase_link/models/product_template.py
  product_form_purchase_link/views/product_product.xml
  product_form_purchase_link/views/product_template.xml
Labels: 14.0

#782 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_analytic_global/__manifest__.py
  purchase_analytic_global/models/purchase.py
Labels: 15.0

#784 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_force_invoiced/README.rst
  purchase_force_invoiced/__init__.py
  purchase_force_invoiced/__manifest__.py
  purchase_force_invoiced/i18n/purchase_force_invoiced.pot
  purchase_force_invoiced/i18n/zh_CN.po
  purchase_force_invoiced/model/__init__.py
  purchase_force_invoiced/model/purchase.py
  purchase_force_invoiced/readme/CONTRIBUTORS.rst
  purchase_force_invoiced/readme/DESCRIPTION.rst
  purchase_force_invoiced/readme/USAGE.rst
  purchase_force_invoiced/reports/__init__.py
  purchase_force_invoiced/reports/purchase_report.py
  purchase_force_invoiced/static/description/icon.png
  purchase_force_invoiced/static/description/index.html
  purchase_force_invoiced/tests/__init__.py
  purchase_force_invoiced/tests/test_purchase_force_invoiced.py
  purchase_force_invoiced/view/purchase_view.xml
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/__init__.py
  purchase_order_supplierinfo_update/__manifest__.py
  purchase_order_supplierinfo_update/i18n/purchase_order_supplierinfo_update.pot
  purchase_order_supplierinfo_update/models/__init__.py
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/readme/CONTRIBUTORS.rst
  purchase_order_supplierinfo_update/readme/DESCRIPTION.rst
  purchase_order_supplierinfo_update/readme/ROADMAP.rst
  purchase_order_supplierinfo_update/readme/USAGE.rst
  purchase_order_supplierinfo_update/static/description/icon.png
  purchase_order_supplierinfo_update/static/description/index.html
  purchase_order_supplierinfo_update/tests/__init__.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_force_invoiced/odoo/addons/purchase_force_invoiced
  setup/purchase_force_invoiced/setup.py
  setup/purchase_order_supplierinfo_update/odoo/addons/purchase_order_supplierinfo_update
  setup/purchase_order_supplierinfo_update/setup.py
Labels: 15.0

#786 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  procurement_purchase_no_grouping/__manifest__.py
  procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py
  purchase_order_product_recommendation/__manifest__.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_qty_change_no_recompute/__manifest__.py
  purchase_order_qty_change_no_recompute/tests/test_purchase_order_qty_change.py
  purchase_partner_selectable_option/__manifest__.py
  purchase_partner_selectable_option/tests/test_purchase_partner_selectable_option.py
  test-requirements.txt
Labels: 15.0

#787 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_order_general_discount/README.rst
  purchase_order_general_discount/__init__.py
  purchase_order_general_discount/__manifest__.py
  purchase_order_general_discount/i18n/es.po
  purchase_order_general_discount/i18n/pt.po
  purchase_order_general_discount/i18n/purchase_order_general_discount.pot
  purchase_order_general_discount/models/__init__.py
  purchase_order_general_discount/models/purchase_order.py
  purchase_order_general_discount/models/res_company.py
  purchase_order_general_discount/models/res_config_settings.py
  purchase_order_general_discount/models/res_partner.py
  purchase_order_general_discount/readme/CONFIGURE.rst
  purchase_order_general_discount/readme/CONTRIBUTORS.rst
  purchase_order_general_discount/readme/DESCRIPTION.rst
  purchase_order_general_discount/readme/USAGE.rst
  purchase_order_general_discount/static/description/icon.png
  purchase_order_general_discount/static/description/index.html
  purchase_order_general_discount/tests/__init__.py
  purchase_order_general_discount/tests/test_purchase_order_general_discount.py
  purchase_order_general_discount/views/purchase_order_view.xml
  purchase_order_general_discount/views/res_config_view.xml
  purchase_order_general_discount/views/res_partner_view.xml
  purchase_order_line_stock_available/README.rst
  purchase_order_line_stock_available/__init__.py
  purchase_order_line_stock_available/__manifest__.py
  purchase_order_line_stock_available/i18n/es.po
  purchase_order_line_stock_available/i18n/pt_BR.po
  purchase_order_line_stock_available/i18n/purchase_order_line_stock_available.pot
  purchase_order_line_stock_available/i18n/sl.po
  purchase_order_line_stock_available/i18n/zh_CN.po
  purchase_order_line_stock_available/models/__init__.py
  purchase_order_line_stock_available/models/purchase.py
  purchase_order_line_stock_available/readme/CONTRIBUTORS.rst
  purchase_order_line_stock_available/readme/DESCRIPTION.rst
  purchase_order_line_stock_available/readme/USAGE.rst
  purchase_order_line_stock_available/static/description/icon.png
  purchase_order_line_stock_available/static/description/index.html
  purchase_order_line_stock_available/tests/__init__.py
  purchase_order_line_stock_available/tests/test_purchase.py
  purchase_order_line_stock_available/views/purchase_view.xml
  purchase_request/__manifest__.py
  purchase_request/models/purchase_request_line.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_order_general_discount/odoo/addons/purchase_order_general_discount
  setup/purchase_order_general_discount/setup.py
  setup/purchase_order_line_stock_available/odoo/addons/purchase_order_line_stock_available
  setup/purchase_order_line_stock_available/setup.py
Labels: 14.0

#788 Syncing from upstream OCA/purchase-workflow (16.0)
  README.md
  purchase_discount/README.rst
  purchase_discount/__init__.py
  purchase_discount/__manifest__.py
  purchase_discount/i18n/de.po
  purchase_discount/i18n/el_GR.po
  purchase_discount/i18n/es.po
  purchase_discount/i18n/es_MX.po
  purchase_discount/i18n/fr.po
  purchase_discount/i18n/fr_CH.po
  purchase_discount/i18n/fr_FR.po
  purchase_discount/i18n/hr.po
  purchase_discount/i18n/it.po
  purchase_discount/i18n/nl.po
  purchase_discount/i18n/pt_BR.po
  purchase_discount/i18n/pt_PT.po
  purchase_discount/i18n/purchase_discount.pot
  purchase_discount/i18n/sl.po
  purchase_discount/i18n/zh_CN.po
  purchase_discount/images/purchase_discount.png
  purchase_discount/models/__init__.py
  purchase_discount/models/product_supplierinfo.py
  purchase_discount/models/purchase_order.py
  purchase_discount/models/res_partner.py
  purchase_discount/models/stock_move.py
  purchase_discount/readme/CONTRIBUTORS.rst
  purchase_discount/readme/DESCRIPTION.rst
  purchase_discount/readme/ROADMAP.rst
  purchase_discount/readme/USAGE.rst
  purchase_discount/report/__init__.py
  purchase_discount/report/purchase_report.py
  purchase_discount/static/description/icon.png
  purchase_discount/static/description/icon.svg
  purchase_discount/static/description/index.html
  purchase_discount/static/description/product_supplierinfo_form.png
  purchase_discount/static/description/res_partner_company_form.png
  purchase_discount/static/description/res_partner_individual_form.png
  purchase_discount/tests/__init__.py
  purchase_discount/tests/test_product_supplierinfo_discount.py
  purchase_discount/tests/test_purchase_discount.py
  purchase_discount/views/product_supplierinfo_view.xml
  purchase_discount/views/purchase_discount_view.xml
  purchase_discount/views/report_purchaseorder.xml
  purchase_discount/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_discount/odoo/addons/purchase_discount
  setup/purchase_discount/setup.py
Labels: 16.0

#789 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_order_line_stock_available/README.rst
  purchase_order_line_stock_available/__init__.py
  purchase_order_line_stock_available/__manifest__.py
  purchase_order_line_stock_available/i18n/es.po
  purchase_order_line_stock_available/i18n/pt_BR.po
  purchase_order_line_stock_available/i18n/purchase_order_line_stock_available.pot
  purchase_order_line_stock_available/i18n/sl.po
  purchase_order_line_stock_available/i18n/zh_CN.po
  purchase_order_line_stock_available/models/__init__.py
  purchase_order_line_stock_available/models/purchase.py
  purchase_order_line_stock_available/readme/CONTRIBUTORS.rst
  purchase_order_line_stock_available/readme/DESCRIPTION.rst
  purchase_order_line_stock_available/readme/USAGE.rst
  purchase_order_line_stock_available/static/description/icon.png
  purchase_order_line_stock_available/static/description/index.html
  purchase_order_line_stock_available/tests/__init__.py
  purchase_order_line_stock_available/tests/test_purchase.py
  purchase_order_line_stock_available/views/purchase_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_order_line_stock_available/odoo/addons/purchase_order_line_stock_available
  setup/purchase_order_line_stock_available/setup.py
Labels: 15.0
