Repository brain-tec/purchase-workflow, pull requests merged in 2022-08, with the labels that each got.

#730 [t131044] PR to import purchase_tier_validation
  purchase_tier_validation/README.rst
  purchase_tier_validation/__init__.py
  purchase_tier_validation/__manifest__.py
  purchase_tier_validation/i18n/es.po
  purchase_tier_validation/i18n/it.po
  purchase_tier_validation/i18n/purchase_tier_validation.pot
  purchase_tier_validation/i18n/zh_CN.po
  purchase_tier_validation/models/__init__.py
  purchase_tier_validation/models/purchase_order.py
  purchase_tier_validation/models/tier_definition.py
  purchase_tier_validation/readme/CONFIGURE.rst
  purchase_tier_validation/readme/CONTRIBUTORS.rst
  purchase_tier_validation/readme/DESCRIPTION.rst
  purchase_tier_validation/readme/INSTALL.rst
  purchase_tier_validation/readme/USAGE.rst
  purchase_tier_validation/static/description/icon.png
  purchase_tier_validation/static/description/index.html
  purchase_tier_validation/tests/__init__.py
  purchase_tier_validation/tests/test_tier_validation.py
  purchase_tier_validation/views/purchase_order_view.xml
  setup/purchase_tier_validation/odoo/addons/purchase_tier_validation
  setup/purchase_tier_validation/setup.py
Labels: 15.0.project_gr_646.t131044

#731 Syncing from upstream OCA/purchase-workflow (13.0)
  README.md
  purchase_propagate_qty/README.rst
  purchase_propagate_qty/__manifest__.py
  purchase_propagate_qty/readme/DESCRIPTION.rst
  purchase_propagate_qty/static/description/index.html
  purchase_propagate_qty/tests/test_purchase_delivery.py
Labels: 13.0

#732 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_discount/__manifest__.py
  purchase_discount/models/purchase_order.py
  purchase_propagate_qty/README.rst
  purchase_propagate_qty/__manifest__.py
  purchase_propagate_qty/readme/DESCRIPTION.rst
  purchase_propagate_qty/static/description/index.html
  purchase_propagate_qty/tests/test_purchase_delivery.py
Labels: 14.0

#733 Syncing from upstream OCA/purchase-workflow (14.0)
  product_form_purchase_link/i18n/fr.po
  purchase_exception/i18n/fr.po
  purchase_order_line_packaging_qty/i18n/fr.po
  purchase_picking_state/i18n/fr.po
  purchase_reception_notify/i18n/fr.po
  purchase_request/i18n/fr.po
  purchase_request_exception/i18n/fr.po
Labels: 14.0

#734 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_request_exception/i18n/fr.po
Labels: 14.0

#735 [t131044] Add purchase_tier_validation module
  purchase_tier_validation/README.rst
  purchase_tier_validation/__init__.py
  purchase_tier_validation/__manifest__.py
  purchase_tier_validation/i18n/es.po
  purchase_tier_validation/i18n/it.po
  purchase_tier_validation/i18n/purchase_tier_validation.pot
  purchase_tier_validation/i18n/zh_CN.po
  purchase_tier_validation/models/__init__.py
  purchase_tier_validation/models/purchase_order.py
  purchase_tier_validation/models/tier_definition.py
  purchase_tier_validation/readme/CONFIGURE.rst
  purchase_tier_validation/readme/CONTRIBUTORS.rst
  purchase_tier_validation/readme/DESCRIPTION.rst
  purchase_tier_validation/readme/INSTALL.rst
  purchase_tier_validation/readme/USAGE.rst
  purchase_tier_validation/static/description/icon.png
  purchase_tier_validation/static/description/index.html
  purchase_tier_validation/tests/__init__.py
  purchase_tier_validation/tests/test_tier_validation.py
  purchase_tier_validation/views/purchase_order_view.xml
  setup/purchase_tier_validation/odoo/addons/purchase_tier_validation
  setup/purchase_tier_validation/setup.py
Labels: 15.0.project_gr_646

#736 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_request/i18n/fr.po
Labels: 14.0

#738 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_order_line_price_history/i18n/fr.po
Labels: 14.0

#739 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_blanket_order/i18n/hr.po
  sale_purchase_force_vendor/README.rst
  sale_purchase_force_vendor/__manifest__.py
  sale_purchase_force_vendor/readme/CONFIGURE.rst
  sale_purchase_force_vendor/readme/DESCRIPTION.rst
  sale_purchase_force_vendor/readme/USAGE.rst
  sale_purchase_force_vendor/static/description/index.html
Labels: 14.0

#740 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_requisition_tier_validation/README.rst
  purchase_requisition_tier_validation/__init__.py
  purchase_requisition_tier_validation/__manifest__.py
  purchase_requisition_tier_validation/i18n/purchase_requisition_tier_validation.pot
  purchase_requisition_tier_validation/i18n/zh_CN.po
  purchase_requisition_tier_validation/models/__init__.py
  purchase_requisition_tier_validation/models/purchase_requisition.py
  purchase_requisition_tier_validation/models/tier_definition.py
  purchase_requisition_tier_validation/readme/CONFIGURE.rst
  purchase_requisition_tier_validation/readme/CONTRIBUTORS.rst
  purchase_requisition_tier_validation/readme/DESCRIPTION.rst
  purchase_requisition_tier_validation/readme/INSTALL.rst
  purchase_requisition_tier_validation/readme/USAGE.rst
  purchase_requisition_tier_validation/static/description/icon.png
  purchase_requisition_tier_validation/static/description/index.html
  purchase_requisition_tier_validation/tests/__init__.py
  purchase_requisition_tier_validation/tests/test_purchase_requisition_tier_validation.py
  purchase_requisition_tier_validation/views/purchase_requisition_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_requisition_tier_validation/odoo/addons/purchase_requisition_tier_validation
  setup/purchase_requisition_tier_validation/setup.py
Labels: 15.0
