Repository brain-tec/purchase-workflow, pull requests merged in 2023-05, with the labels that each got.

#1003 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/de.po
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/fr.po
  purchase_order_secondary_unit/i18n/ja.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/reports/purchase_order_templates.xml
  purchase_order_secondary_unit/reports/purchase_quotation_templates.xml
Labels: 15.0

#1004 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_order_approved/i18n/fr.po
Labels: 16.0

#1005 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  sale_purchase_force_vendor/__manifest__.py
  sale_purchase_force_vendor/models/stock_move.py
Labels: 15.0

#1006 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_requisition_auto_rfq/__manifest__.py
  purchase_requisition_auto_rfq/demo/product_product.xml
  purchase_requisition_auto_rfq/i18n/fr.po
  purchase_requisition_auto_rfq/i18n/purchase_requisition_auto_rfq.pot
  purchase_requisition_auto_rfq/models/purchase_requisition.py
  purchase_requisition_auto_rfq/view/purchase_requisition.xml
Labels: 14.0

#1007 Syncing from upstream OCA/purchase-workflow (16.0)
  README.md
  purchase_order_product_recommendation/README.rst
  purchase_order_product_recommendation/__init__.py
  purchase_order_product_recommendation/__manifest__.py
  purchase_order_product_recommendation/i18n/es.po
  purchase_order_product_recommendation/i18n/purchase_order_product_recommendation.pot
  purchase_order_product_recommendation/readme/CONTRIBUTORS.rst
  purchase_order_product_recommendation/readme/DESCRIPTION.rst
  purchase_order_product_recommendation/readme/USAGE.rst
  purchase_order_product_recommendation/security/ir.model.access.csv
  purchase_order_product_recommendation/static/description/icon.png
  purchase_order_product_recommendation/static/description/index.html
  purchase_order_product_recommendation/tests/__init__.py
  purchase_order_product_recommendation/tests/test_recommendation.py
  purchase_order_product_recommendation/views/purchase_order_view.xml
  purchase_order_product_recommendation/wizards/__init__.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation.py
  purchase_order_product_recommendation/wizards/purchase_order_recommendation_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_order_product_recommendation/odoo/addons/purchase_order_product_recommendation
  setup/purchase_order_product_recommendation/setup.py
Labels: 16.0

#1008 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_order_product_recommendation/i18n/es.po
Labels: 16.0

#1009 Syncing from upstream OCA/purchase-workflow (12.0)
  purchase_request/i18n/it.po
Labels: 12.0

#1010 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_order_type/i18n/it.po
Labels: 14.0

#1011 Syncing from upstream OCA/purchase-workflow (16.0)
  README.md
  purchase_order_uninvoiced_amount/README.rst
  purchase_order_uninvoiced_amount/__init__.py
  purchase_order_uninvoiced_amount/__manifest__.py
  purchase_order_uninvoiced_amount/i18n/en_US.po
  purchase_order_uninvoiced_amount/i18n/es.po
  purchase_order_uninvoiced_amount/i18n/purchase_order_uninvoiced_amount.pot
  purchase_order_uninvoiced_amount/models/__init__.py
  purchase_order_uninvoiced_amount/models/purchase_order.py
  purchase_order_uninvoiced_amount/readme/CONTRIBUTORS.rst
  purchase_order_uninvoiced_amount/readme/DESCRIPTION.rst
  purchase_order_uninvoiced_amount/static/description/icon.png
  purchase_order_uninvoiced_amount/static/description/index.html
  purchase_order_uninvoiced_amount/tests/__init__.py
  purchase_order_uninvoiced_amount/tests/test_purchase_order_uninvoiced_amount.py
  purchase_order_uninvoiced_amount/views/purchase_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_order_uninvoiced_amount/odoo/addons/purchase_order_uninvoiced_amount
  setup/purchase_order_uninvoiced_amount/setup.py
Labels: 16.0

#1013 Syncing from upstream OCA/purchase-workflow (11.0)
  purchase_request/i18n/it.po
Labels: 11.0

#1016 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_request/i18n/it.po
Labels: 14.0

#1017 Syncing from upstream OCA/purchase-workflow (15.0)
  purchase_request/i18n/it.po
Labels: 15.0

#1018 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_request/i18n/it.po
Labels: 16.0

#1019 Syncing from upstream OCA/purchase-workflow (12.0)
  purchase_request/i18n/it.po
Labels: 12.0

#1020 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_line_reassign/README.rst
  purchase_line_reassign/__init__.py
  purchase_line_reassign/__manifest__.py
  purchase_line_reassign/i18n/es.po
  purchase_line_reassign/i18n/purchase_line_reassign.pot
  purchase_line_reassign/readme/CONFIGURE.rst
  purchase_line_reassign/readme/CONTRIBUTORS.rst
  purchase_line_reassign/readme/DESCRIPTION.rst
  purchase_line_reassign/readme/USAGE.rst
  purchase_line_reassign/security/ir.model.access.csv
  purchase_line_reassign/static/description/icon.png
  purchase_line_reassign/static/description/index.html
  purchase_line_reassign/tests/__init__.py
  purchase_line_reassign/tests/test_reassign.py
  purchase_line_reassign/wizards/__init__.py
  purchase_line_reassign/wizards/purchase_line_reassign_view.xml
  purchase_line_reassign/wizards/purchase_line_reassign_wiz.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_line_reassign/odoo/addons/purchase_line_reassign
  setup/purchase_line_reassign/setup.py
Labels: 15.0

#1021 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_order_line_price_history/__manifest__.py
  purchase_order_line_price_history/views/purchase_views.xml
Labels: 14.0

#1022 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_stock_secondary_unit/README.rst
  purchase_stock_secondary_unit/__init__.py
  purchase_stock_secondary_unit/__manifest__.py
  purchase_stock_secondary_unit/i18n/de.po
  purchase_stock_secondary_unit/i18n/es.po
  purchase_stock_secondary_unit/i18n/purchase_stock_secondary_unit.pot
  purchase_stock_secondary_unit/models/__init__.py
  purchase_stock_secondary_unit/models/purchase_order_line.py
  purchase_stock_secondary_unit/models/stock_move.py
  purchase_stock_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_stock_secondary_unit/readme/DESCRIPTION.rst
  purchase_stock_secondary_unit/readme/USAGE.rst
  purchase_stock_secondary_unit/static/description/icon.png
  purchase_stock_secondary_unit/static/description/index.html
  purchase_stock_secondary_unit/tests/__init__.py
  purchase_stock_secondary_unit/tests/test_purchase_stock_secondary_unit.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_stock_secondary_unit/odoo/addons/purchase_stock_secondary_unit
  setup/purchase_stock_secondary_unit/setup.py
Labels: 15.0

#1023 Syncing from upstream OCA/purchase-workflow (10.0)
  purchase_cancel_reason/i18n/it.po
  purchase_request_to_procurement/i18n/it.po
  purchase_request_to_rfq/i18n/it.po
Labels: 10.0

#1024 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_request/i18n/it.po
  purchase_substate/README.rst
  purchase_substate/__init__.py
  purchase_substate/__manifest__.py
  purchase_substate/data/purchase_substate_data.xml
  purchase_substate/data/purchase_substate_demo.xml
  purchase_substate/data/purchase_substate_mail_template_data.xml
  purchase_substate/i18n/purchase_substate.pot
  purchase_substate/models/__init__.py
  purchase_substate/models/purchase_order.py
  purchase_substate/readme/CONTRIBUTORS.rst
  purchase_substate/readme/DESCRIPTION.rst
  purchase_substate/readme/USAGE.rst
  purchase_substate/static/description/icon.png
  purchase_substate/static/description/index.html
  purchase_substate/tests/__init__.py
  purchase_substate/tests/test_purchase_substate.py
  purchase_substate/views/purchase_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_substate/odoo/addons/purchase_substate
  setup/purchase_substate/setup.py
Labels: 14.0

#1025 Syncing from upstream OCA/purchase-workflow (15.0)
  purchase_stock_secondary_unit/i18n/de.po
  purchase_stock_secondary_unit/i18n/es.po
Labels: 15.0

#1026 Syncing from upstream OCA/purchase-workflow (12.0)
  procurement_purchase_no_grouping/i18n/it.po
  purchase_line_procurement_group/i18n/it.po
  purchase_request/i18n/it.po
  purchase_triple_discount/i18n/it.po
Labels: 12.0

#1027 Syncing from upstream OCA/purchase-workflow (13.0)
  purchase_discount/i18n/it.po
  purchase_request/i18n/it.po
  purchase_triple_discount/i18n/it.po
Labels: 13.0

#1028 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_discount/i18n/it.po
  purchase_request/i18n/it.po
Labels: 14.0

#1029 Syncing from upstream OCA/purchase-workflow (15.0)
  product_supplier_code_purchase/i18n/it.po
  purchase_discount/i18n/it.po
  purchase_request/i18n/it.po
  purchase_triple_discount/i18n/it.po
Labels: 15.0

#1031 Syncing from upstream OCA/purchase-workflow (16.0)
  README.md
  purchase_order_no_zero_price/README.rst
  purchase_order_no_zero_price/__init__.py
  purchase_order_no_zero_price/__manifest__.py
  purchase_order_no_zero_price/i18n/purchase_order_no_zero_price.pot
  purchase_order_no_zero_price/models/__init__.py
  purchase_order_no_zero_price/models/purchase_order_line.py
  purchase_order_no_zero_price/readme/CONTRIBUTORS.rst
  purchase_order_no_zero_price/readme/DESCRIPTION.rst
  purchase_order_no_zero_price/readme/USAGE.rst
  purchase_order_no_zero_price/static/description/icon.png
  purchase_order_no_zero_price/static/description/index.html
  purchase_order_no_zero_price/tests/__init__.py
  purchase_order_no_zero_price/tests/test_purchase_order_no_zero_price.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_order_no_zero_price/odoo/addons/purchase_order_no_zero_price
  setup/purchase_order_no_zero_price/setup.py
Labels: 16.0

#1032 Syncing from upstream OCA/purchase-workflow (10.0)
  purchase_landed_cost/i18n/it.po
Labels: 10.0

#1033 Syncing from upstream OCA/purchase-workflow (12.0)
  purchase_request/i18n/it.po
Labels: 12.0

#1034 Syncing from upstream OCA/purchase-workflow (13.0)
  purchase_request/i18n/it.po
Labels: 13.0

#1035 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_request/i18n/it.po
Labels: 14.0

#1036 Syncing from upstream OCA/purchase-workflow (15.0)
  purchase_request/i18n/it.po
Labels: 15.0

#1037 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_request/i18n/it.po
Labels: 16.0

#1038 Syncing from upstream OCA/purchase-workflow (12.0)
  purchase_request/i18n/it.po
Labels: 12.0

#1039 Syncing from upstream OCA/purchase-workflow (13.0)
  purchase_request/i18n/it.po
Labels: 13.0

#1040 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_reception_status/__manifest__.py
  purchase_reception_status/views/purchase_order.xml
  purchase_request/i18n/it.po
Labels: 14.0

#1041 Syncing from upstream OCA/purchase-workflow (15.0)
  purchase_request/i18n/it.po
Labels: 15.0

#1042 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_order_uninvoiced_amount/i18n/es.po
  purchase_request/i18n/it.po
Labels: 16.0

#1043 [16.0][MIG] purchase_order_secondary_unit: Migration to 16.0
  purchase_order_secondary_unit/README.rst
  purchase_order_secondary_unit/__init__.py
  purchase_order_secondary_unit/__manifest__.py
  purchase_order_secondary_unit/i18n/de.po
  purchase_order_secondary_unit/i18n/es.po
  purchase_order_secondary_unit/i18n/fr.po
  purchase_order_secondary_unit/i18n/ja.po
  purchase_order_secondary_unit/i18n/purchase_order_secondary_unit.pot
  purchase_order_secondary_unit/models/__init__.py
  purchase_order_secondary_unit/models/product_product.py
  purchase_order_secondary_unit/models/product_template.py
  purchase_order_secondary_unit/models/purchase_order.py
  purchase_order_secondary_unit/readme/CONTRIBUTORS.rst
  purchase_order_secondary_unit/readme/DESCRIPTION.rst
  purchase_order_secondary_unit/readme/USAGE.rst
  purchase_order_secondary_unit/reports/purchase_order_templates.xml
  purchase_order_secondary_unit/reports/purchase_quotation_templates.xml
  purchase_order_secondary_unit/static/description/icon.png
  purchase_order_secondary_unit/static/description/index.html
  purchase_order_secondary_unit/test-requirements.txt
  purchase_order_secondary_unit/tests/__init__.py
  purchase_order_secondary_unit/tests/test_purchase_order_secondary_unit.py
  purchase_order_secondary_unit/views/product_views.xml
  purchase_order_secondary_unit/views/purchase_order_views.xml
  setup/purchase_order_secondary_unit/odoo/addons/purchase_order_secondary_unit
  setup/purchase_order_secondary_unit/setup.py
Labels: 16.0.project_ba_688

#1044 Syncing from upstream OCA/purchase-workflow (14.0)
  .github/workflows/test.yml
  README.md
  purchase_order_type_dashboard/README.rst
  purchase_order_type_dashboard/__init__.py
  purchase_order_type_dashboard/__manifest__.py
  purchase_order_type_dashboard/demo/purchase_order_type_dashboard.xml
  purchase_order_type_dashboard/i18n/es.po
  purchase_order_type_dashboard/i18n/purchase_order_type_dashboard.pot
  purchase_order_type_dashboard/models/__init__.py
  purchase_order_type_dashboard/models/purchase_order_type.py
  purchase_order_type_dashboard/readme/CONTRIBUTORS.rst
  purchase_order_type_dashboard/readme/DESCRIPTION.rst
  purchase_order_type_dashboard/static/description/icon.png
  purchase_order_type_dashboard/static/description/index.html
  purchase_order_type_dashboard/tests/__init__.py
  purchase_order_type_dashboard/tests/test_purchase_order_type_dashboard.py
  purchase_order_type_dashboard/views/menu_purchase_order.xml
  purchase_order_type_dashboard/views/view_purchase_order.xml
  purchase_order_type_dashboard/views/view_purchase_order_type.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_order_type_dashboard/odoo/addons/purchase_order_type_dashboard
  setup/purchase_order_type_dashboard/setup.py
Labels: 14.0

#1045 Syncing from upstream OCA/purchase-workflow (8.0)
  procurement_batch_generator/i18n/it.po
  purchase_add_product_supplierinfo/i18n/it.po
Labels: 8.0

#1046 Syncing from upstream OCA/purchase-workflow (13.0)
  purchase_request/i18n/it.po
Labels: 13.0

#1047 Syncing from upstream OCA/purchase-workflow (14.0)
  procurement_batch_generator/i18n/it.po
  purchase_order_secondary_unit/i18n/pt_BR.po
  purchase_stock_secondary_unit/i18n/pt_BR.po
Labels: 14.0

#1048 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_order_secondary_unit/i18n/pt_BR.po
  purchase_stock_secondary_unit/i18n/pt_BR.po
Labels: 14.0

#1049 Syncing from upstream OCA/purchase-workflow (8.0)
  procurement_batch_generator/i18n/it.po
  purchase_add_product_supplierinfo/i18n/it.po
  purchase_request_to_requisition/i18n/it.po
  purchase_rfq_bid_workflow/i18n/it.po
Labels: 8.0

#1050 Syncing from upstream OCA/purchase-workflow (11.0)
  purchase_allowed_product/i18n/it.po
  purchase_order_type/i18n/it.po
  purchase_request/i18n/it.po
Labels: 11.0

#1051 Syncing from upstream OCA/purchase-workflow (10.0)
  purchase_cancel_reason/i18n/it.po
  purchase_order_approval_block/i18n/it.po
  purchase_request/i18n/it.po
  purchase_request_to_rfq/i18n/it.po
Labels: 10.0

#1052 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_order_vendor_product/i18n/ca.po
Labels: 14.0

#1053 Syncing from upstream OCA/purchase-workflow (13.0)
  purchase_request_tier_validation/i18n/it.po
Labels: 13.0

#1054 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_order_line_sequence/i18n/es.po
  purchase_request_tier_validation/i18n/it.po
  purchase_tier_validation/i18n/it.po
Labels: 14.0

#1055 Syncing from upstream OCA/purchase-workflow (15.0)
  purchase_request_tier_validation/i18n/it.po
Labels: 15.0

#1056 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_request_tier_validation/i18n/it.po
Labels: 16.0

#1057 Syncing from upstream OCA/purchase-workflow (13.0)
  purchase_request_department/i18n/it.po
Labels: 13.0

#1058 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_request_department/i18n/it.po
Labels: 14.0

#1059 Syncing from upstream OCA/purchase-workflow (15.0)
  purchase_request_department/i18n/it.po
Labels: 15.0
