Repository brain-tec/purchase-workflow, pull requests merged in 2025-04, with the labels that each got.

#1731 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_advance_payment/README.rst
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: 14.0

#1733 Syncing from upstream OCA/purchase-workflow (18.0)
  README.md
  purchase_advance_payment/README.rst
  purchase_advance_payment/__init__.py
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/data/ir_config_parameter.xml
  purchase_advance_payment/i18n/es.po
  purchase_advance_payment/i18n/fr.po
  purchase_advance_payment/i18n/it.po
  purchase_advance_payment/i18n/pt_BR.po
  purchase_advance_payment/i18n/purchase_advance_payment.pot
  purchase_advance_payment/models/__init__.py
  purchase_advance_payment/models/account_move.py
  purchase_advance_payment/models/payment.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/models/res_config_settings.py
  purchase_advance_payment/pyproject.toml
  purchase_advance_payment/readme/CONTRIBUTORS.md
  purchase_advance_payment/readme/CREDITS.md
  purchase_advance_payment/readme/DESCRIPTION.md
  purchase_advance_payment/readme/USAGE.md
  purchase_advance_payment/security/ir.model.access.csv
  purchase_advance_payment/static/description/icon.png
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/__init__.py
  purchase_advance_payment/tests/test_purchase_advance_payment.py
  purchase_advance_payment/views/account_payment_views.xml
  purchase_advance_payment/views/purchase_view.xml
  purchase_advance_payment/views/res_config_settings_views.xml
  purchase_advance_payment/wizard/__init__.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard.py
  purchase_advance_payment/wizard/purchase_advance_payment_wizard_view.xml
  purchase_fop_shipping/README.rst
  purchase_fop_shipping/__init__.py
  purchase_fop_shipping/__manifest__.py
  purchase_fop_shipping/i18n/de.po
  purchase_fop_shipping/i18n/es.po
  purchase_fop_shipping/i18n/es_PE.po
  purchase_fop_shipping/i18n/fr.po
  purchase_fop_shipping/i18n/fr_BE.po
  purchase_fop_shipping/i18n/gl.po
  purchase_fop_shipping/i18n/hr.po
  purchase_fop_shipping/i18n/it.po
  purchase_fop_shipping/i18n/nl.po
  purchase_fop_shipping/i18n/nl_NL.po
  purchase_fop_shipping/i18n/pt_BR.po
  purchase_fop_shipping/i18n/purchase_fop_shipping.pot
  purchase_fop_shipping/i18n/ro.po
  purchase_fop_shipping/i18n/sl.po
  purchase_fop_shipping/i18n/vi_VN.po
  purchase_fop_shipping/models/__init__.py
  purchase_fop_shipping/models/partner.py
  purchase_fop_shipping/models/purchase.py
  purchase_fop_shipping/pyproject.toml
  purchase_fop_shipping/security/res_groups.xml
  purchase_fop_shipping/static/description/icon.png
  purchase_fop_shipping/tests/__init__.py
  purchase_fop_shipping/tests/test_fop_shipping.py
  purchase_fop_shipping/views/purchase_order.xml
  purchase_fop_shipping/views/res_partner.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#1734 Syncing from upstream OCA/purchase-workflow (17.0)
  README.md
  purchase_advance_payment/README.rst
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/data/ir_config_parameter.xml
  purchase_advance_payment/static/description/index.html
  purchase_manual_currency/i18n/it.po
Labels: 17.0

#1735 Syncing from upstream OCA/purchase-workflow (17.0)
  purchase_stock_manual_currency/i18n/it.po
Labels: 17.0

#1736 Syncing from upstream OCA/purchase-workflow (16.0)
  README.md
  purchase_manual_delivery/README.rst
  purchase_manual_delivery/__manifest__.py
  purchase_manual_delivery/report/stock_forecasted.py
  purchase_manual_delivery/static/description/index.html
Labels: 16.0

#1737 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_exception/i18n/pt_BR.po
  purchase_invoice_new_picking_line/i18n/it.po
  purchase_request/i18n/pt_BR.po
Labels: 16.0

#1738 Syncing from upstream OCA/purchase-workflow (18.0)
  README.md
  purchase_order_line_menu/README.rst
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/__init__.py
  purchase_order_supplierinfo_update/__manifest__.py
  purchase_order_supplierinfo_update/i18n/it.po
  purchase_order_supplierinfo_update/i18n/pt_BR.po
  purchase_order_supplierinfo_update/i18n/purchase_order_supplierinfo_update.pot
  purchase_order_supplierinfo_update/models/__init__.py
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/pyproject.toml
  purchase_order_supplierinfo_update/readme/CONTRIBUTORS.md
  purchase_order_supplierinfo_update/readme/DESCRIPTION.md
  purchase_order_supplierinfo_update/readme/ROADMAP.md
  purchase_order_supplierinfo_update/readme/USAGE.md
  purchase_order_supplierinfo_update/static/description/icon.png
  purchase_order_supplierinfo_update/static/description/index.html
  purchase_order_supplierinfo_update/tests/__init__.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
  purchase_order_type/README.rst
  purchase_request_department/README.rst
  setup/_metapackage/pyproject.toml
Labels: 18.0

#1739 Syncing from upstream OCA/purchase-workflow (14.0)
  purchase_blanket_order/i18n/it.po
Labels: 14.0

#1740 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_blanket_order/i18n/it.po
Labels: 16.0

#1742 Syncing from upstream OCA/purchase-workflow (18.0)
  README.md
  purchase_blanket_order/i18n/it.po
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/__manifest__.py
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/readme/DESCRIPTION.md
  purchase_order_supplierinfo_update/readme/USAGE.md
  purchase_order_supplierinfo_update/static/description/index.html
Labels: 18.0

#1745 Syncing from upstream OCA/purchase-workflow (15.0)
  README.md
  purchase_advance_payment/README.rst
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: 15.0

#1746 Syncing from upstream OCA/purchase-workflow (17.0)
  README.md
  purchase_stock_price_unit_sync/README.rst
  purchase_stock_price_unit_sync/__init__.py
  purchase_stock_price_unit_sync/__manifest__.py
  purchase_stock_price_unit_sync/i18n/it.po
  purchase_stock_price_unit_sync/i18n/purchase_stock_price_unit_sync.pot
  purchase_stock_price_unit_sync/models/__init__.py
  purchase_stock_price_unit_sync/models/purchase_order.py
  purchase_stock_price_unit_sync/pyproject.toml
  purchase_stock_price_unit_sync/readme/CONTRIBUTORS.md
  purchase_stock_price_unit_sync/readme/DESCRIPTION.md
  purchase_stock_price_unit_sync/static/description/icon.png
  purchase_stock_price_unit_sync/static/description/index.html
  purchase_stock_price_unit_sync/tests/__init__.py
  purchase_stock_price_unit_sync/tests/test_purchase_stock_price_unit_sync.py
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1747 Syncing from upstream OCA/purchase-workflow (16.0)
  product_main_seller/i18n/nl.po
Labels: 16.0

#1748 Syncing from upstream OCA/purchase-workflow (18.0)
  purchase_request_tier_validation/i18n/tr.po
  purchase_tier_validation/i18n/tr.po
Labels: 18.0

#1749 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_order_approved/i18n/tr.po
Labels: 16.0

#1750 Syncing from upstream OCA/purchase-workflow (16.0)
  README.md
  purchase_advance_payment/README.rst
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: 16.0

#1751 Syncing from upstream OCA/purchase-workflow (17.0)
  README.md
  purchase_advance_payment/README.rst
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/static/description/index.html
  purchase_advance_payment/tests/test_purchase_advance_payment.py
Labels: 17.0

#1752 Syncing from upstream OCA/purchase-workflow (14.0)
  README.md
  purchase_advance_payment/README.rst
  purchase_advance_payment/__manifest__.py
  purchase_advance_payment/models/purchase_order.py
  purchase_advance_payment/static/description/index.html
Labels: 14.0

#1754 Syncing from upstream OCA/purchase-workflow (17.0)
  README.md
  purchase_lot/README.rst
  purchase_lot/__init__.py
  purchase_lot/__manifest__.py
  purchase_lot/i18n/es.po
  purchase_lot/i18n/it.po
  purchase_lot/i18n/purchase_lot.pot
  purchase_lot/models/__init__.py
  purchase_lot/models/purchase_order_line.py
  purchase_lot/models/stock_rule.py
  purchase_lot/pyproject.toml
  purchase_lot/readme/CONTRIBUTORS.md
  purchase_lot/readme/DESCRIPTION.md
  purchase_lot/static/description/icon.png
  purchase_lot/static/description/index.html
  purchase_lot/tests/__init__.py
  purchase_lot/tests/test_purchase_lot.py
  purchase_lot/views/purchase_order_view.xml
  purchase_order_supplierinfo_update/README.rst
  purchase_order_supplierinfo_update/__init__.py
  purchase_order_supplierinfo_update/__manifest__.py
  purchase_order_supplierinfo_update/i18n/it.po
  purchase_order_supplierinfo_update/i18n/pt_BR.po
  purchase_order_supplierinfo_update/i18n/purchase_order_supplierinfo_update.pot
  purchase_order_supplierinfo_update/models/__init__.py
  purchase_order_supplierinfo_update/models/purchase_order.py
  purchase_order_supplierinfo_update/pyproject.toml
  purchase_order_supplierinfo_update/readme/CONTRIBUTORS.md
  purchase_order_supplierinfo_update/readme/DESCRIPTION.md
  purchase_order_supplierinfo_update/readme/ROADMAP.md
  purchase_order_supplierinfo_update/readme/USAGE.md
  purchase_order_supplierinfo_update/static/description/icon.png
  purchase_order_supplierinfo_update/static/description/index.html
  purchase_order_supplierinfo_update/tests/__init__.py
  purchase_order_supplierinfo_update/tests/test_purchase_order_supplierinfo_update.py
  purchase_order_weight_volume/README.rst
  purchase_order_weight_volume/__init__.py
  purchase_order_weight_volume/__manifest__.py
  purchase_order_weight_volume/i18n/es.po
  purchase_order_weight_volume/i18n/it.po
  purchase_order_weight_volume/i18n/purchase_order_weight_volume.pot
  purchase_order_weight_volume/models/__init__.py
  purchase_order_weight_volume/models/purchase_order.py
  purchase_order_weight_volume/models/res_company.py
  purchase_order_weight_volume/models/res_config_settings.py
  purchase_order_weight_volume/pyproject.toml
  purchase_order_weight_volume/readme/CONTRIBUTORS.md
  purchase_order_weight_volume/readme/CREDITS.md
  purchase_order_weight_volume/readme/DESCRIPTION.md
  purchase_order_weight_volume/readme/USAGE.md
  purchase_order_weight_volume/report/purchase_report_templates.xml
  purchase_order_weight_volume/static/description/icon.png
  purchase_order_weight_volume/static/description/index.html
  purchase_order_weight_volume/tests/__init__.py
  purchase_order_weight_volume/tests/test_purchase_order_weight_volume.py
  purchase_order_weight_volume/views/purchase_order_view.xml
  purchase_order_weight_volume/views/res_config_settings_views.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1755 Creating project branch
  purchase_partner_incoterm/README.rst
  purchase_partner_incoterm/__init__.py
  purchase_partner_incoterm/__manifest__.py
  purchase_partner_incoterm/i18n/it.po
  purchase_partner_incoterm/i18n/purchase_partner_incoterm.pot
  purchase_partner_incoterm/models/__init__.py
  purchase_partner_incoterm/models/purchase_order.py
  purchase_partner_incoterm/models/res_partner.py
  purchase_partner_incoterm/pyproject.toml
  purchase_partner_incoterm/readme/CONTRIBUTORS.md
  purchase_partner_incoterm/readme/CREDITS.md
  purchase_partner_incoterm/readme/DESCRIPTION.md
  purchase_partner_incoterm/static/description/icon.png
  purchase_partner_incoterm/static/description/index.html
  purchase_partner_incoterm/tests/__init__.py
  purchase_partner_incoterm/tests/test_purchase_partner_incoterm.py
  purchase_partner_incoterm/views/partner_view.xml
  purchase_partner_incoterm/views/purchase_view.xml
Labels: 18.0.project_pe_692

#1756 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_only_by_packaging/i18n/de.po
Labels: 16.0

#1757 Syncing from upstream OCA/purchase-workflow (16.0)
  purchase_request/i18n/it.po
  purchase_split_by_route/i18n/it.po
Labels: 16.0

#1758 Syncing from upstream OCA/purchase-workflow (17.0)
  README.md
  purchase_open_qty/README.rst
  purchase_open_qty/__manifest__.py
  purchase_open_qty/init_hook.py
  purchase_open_qty/static/description/index.html
Labels: 17.0
